### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by vko-online** [techniq/react-fetch-component#31]
Was curious if api could be extended, with things like `skip, fetchMore, refetch` which are implemented in react-apollo/Query

**Comment by techniq** [comment]
@vko-online It is definitely not abandoned, but hasn't been a priority for me either.  I actively use it on all my projects (directly or indirectly through [react-odata](https://github.com/techniq/react-odata) for example).

With that said, I haven't released version 8 yet as I've been contemplating giving it a better name than `react-fetch-component` since it now supports hooks (and is how I primarily use it nowadays).  I've also written a graphql layer on it (similar to my `react-odata`) and wanted to release all of them together.  I've been dogfooding the graphql one since at least January with good success as well.  I've debated on releasing them as scoped packages (`@techniq/react-fetch`, `@techniq/react-fetch-graphql`, etc) but not sure I want to or not.

With that said, what does `skip`, `fetchMore`, and `refetch` each do?  We already have support for calling [fetch()](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L162-L221) (used to refetch data or to issue the request when `manual={true}` is set) and [deps](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L501-L572) which issues a request if changed (useful to re-request when a POST body data changes).

One thing the project could use is some improved docs (what's in the README does not represent all the features / functionality) and always welcome a PR.

**Comment by vko-online** [comment]
skip = ability to skip request if user not authorized for example
fetchMore = pagination
refetch = refetch previous query

i'm talking in react-native scope, and refetch/fetchMore are very useful for list with refresh controls
